package com.etsmtl.log635.labo1.investigation

import org.slf4j.Logger
import com.etsmtl.log635.labo1.helloworld.*
import com.etsmtl.log635.labo1.investigation.model.*

global Logger log;

rule "Test"
    when
        Crime(lieu != null, $lieu: lieu)
        Crime(datetimeFrom != null, datetimeTo != null, $dtFrom: datetimeFrom, $dtTo: datetimeTo)
        Crime(objet != null, $arme: objet)
        Evenement(
         lieu.compareTo($lieu) == 0,
         lieu != null,
         datetimeTo == null,
         datetimeFrom != null,
         $atTime: datetimeFrom,
         $pers: personnage,
         personnage != null
        )
        eval($atTime.isAfter($dtFrom))
        eval($atTime.isBefore($dtTo))
        Evenement(
            personnage != null,
            objet != null,
            personnage.compareTo($pers)==0,
            objet.compareTo($arme)==0
        )
        $s: Personnage(nom == null)
    then
        System.out.println("Personnage "+$pers.getNom()+" is suspect ");
        $pers.setSuspect(true);
        $s.setNom($pers.getNom());
        $s.setSuspect(true);
end

rule "Personnage détient arme du crime"
    when
        Crime(objet != null, $arme: objet)
        Personnage(
            $nomArme: getArme().nom)
        $p: Personnage()
        eval($nomArme ==  $arme)
    then
        $p.setSuspect(true);//Should be "setHasCrimeWeapon()"
        System.out.println("Personnage "+ $p.getNom() + "détient l'arme du crime.");
        update($p)
 end

 rule "Personnage était sur le lieu du crime"
    when
        Crime(datetimeFrom != null, $startTime: datetimeFrom)
        Crime(datetimeTo != null, $endTime: datetimeTo)
        Crime(lieu != null, $lieu: lieu)
        Evenement(lieu != null)
        Evenement(lieu == $lieu)
        Evenement(personnage != null, $p: personnage)
    then
        $p.setSuspect(true);  ///Should be setWasAtCrimeScene
        System.out.println("Personnage "+ $p.getNom() + "était sur le lieu du crime.");
        update($p);
 end

