package com.etsmtl.log635.labo1.investigation

import org.slf4j.Logger
import com.etsmtl.log635.labo1.investigation.model.*

global Logger log;

rule "Test"
    when
        Crime(lieu != null, $lieu: lieu)
        Crime(datetimeFrom != null, datetimeTo != null, $dtFrom: datetimeFrom, $dtTo: datetimeTo)
        Crime(objet != null, $arme: objet)
        Evenement(
         lieu.compareTo($lieu) == 0,
         lieu != null,
         datetimeTo == null,
         datetimeFrom != null,
         $atTime: datetimeFrom,
         $pers: personnage,
         personnage != null
        )
        eval($atTime.isAfter($dtFrom))
        eval($atTime.isBefore($dtTo))
        Evenement(
            personnage != null,
            objet != null,
            personnage.compareTo($pers)==0,
            objet.compareTo($arme)==0
        )
        $s: Personnage(nom == null)
    then
        System.out.println("Personnage "+$pers.getNom()+" is suspect ");
        $pers.setSuspect(true);
        $s.setNom($pers.getNom());
        $s.setSuspect(true);
end



